SRVPGMs := FARTICLE.SRVPGM FCOUNTRY.SRVPGM FCUSTOMER.SRVPGM FFAMILLY.SRVPGM FPROVIDER.SRVPGM XML.SRVPGM

FARTICLE.SRVPGM: $(d)/farticle.bnd ART300.MODULE ART301.MODULE FFAMILLY.SRVPGM
FARTICLE.SRVPGM: TEXT = 'Function Article'
FCOUNTRY.SRVPGM: $(d)/fcountry.bnd COU300.MODULE COU301.MODULE
FCOUNTRY.SRVPGM: TEXT = 'Functions Country'
FCUSTOMER.SRVPGM: $(d)/fcustomer.bnd CUS300.MODULE CUS301.MODULE
FCUSTOMER.SRVPGM: TEXT = 'Functions Customer'
FFAMILLY.SRVPGM: $(d)/ffamilly.bnd FAM300.MODULE FAM301.MODULE
FFAMILLY.SRVPGM: TEXT = 'Functions Family'
FPROVIDER.SRVPGM: $(d)/fprovider.bnd PRO300.MODULE
FPROVIDER.SRVPGM: TEXT = 'Functions Provider'
TXT.SRVPGM: $(d)/txt.bnd TXT001.MODULE 
XML.SRVPGM: $(d)/xml.bnd XML001.MODULE TXT.SRVPGM